feat(auth-pages): assets and auth pages integration
om-ma/natures-flavors pull request #1
Opened 2021-11-02 07:53 UTC by hamzanaveed9

feat(auth-pages):

-Asset integration
-Auth pages integration

2021-11-02 08:30 UTC, umairrazam commented on app/views/spree/layouts/spree_application.html.erb
> +
remove extra lines

2021-11-02 08:31 UTC, umairrazam commented on app/views/spree/layouts/spree_application.html.erb
> +    <div class>
remove extra clases

2021-11-02 08:32 UTC, umairrazam commented on app/views/spree/layouts/spree_application.html.erb
> +</html>
add lof

2021-11-02 08:32 UTC, umairrazam commented on app/views/spree/shared/_bottom_footer.html.erb
> +</div>
lof

2021-11-02 08:32 UTC, umairrazam commented on app/views/spree/shared/_footer.html.erb
> +  <%= render partial: 'spree/shared/upper_footer' %>
code indentation

2021-11-02 08:33 UTC, umairrazam commented on app/views/spree/shared/_header.html.erb
> +
remove extra lines

2021-11-02 08:34 UTC, umairrazam commented on app/views/spree/shared/_login.html.erb
> +      <fieldset id="password-credentials">
code indentation

2021-11-02 08:34 UTC, umairrazam commented on app/views/spree/shared/_main_nav_bar.html.erb
> +
remove extra lines

2021-11-02 08:36 UTC, umairrazam commented on app/views/spree/shared/_search.html.erb
> +<div class="header-search tablet-hide">
code indentation

2021-11-02 08:36 UTC, umairrazam commented on app/views/spree/shared/_sign_in_header.html.erb
> +<ol class="breadcrumb">
code indentation

2021-11-02 08:37 UTC, umairrazam commented on app/views/spree/shared/_upper_footer.html.erb
> +  <div></div>
remove extra divs

2021-11-02 08:38 UTC, umairrazam commented on app/views/spree/user_passwords/edit.html.erb
> +               <div>
code indentation

2021-11-02 08:39 UTC, umairrazam commented on app/views/spree/user_passwords/new.html.erb
> +         <div id="forgot-password">
code indentation

2021-11-02 08:40 UTC, umairrazam commented on app/views/spree/user_passwords/new.html.erb
> +                  <% end %>
end tag wrong placement

2021-11-02 08:41 UTC, umairrazam commented on app/views/spree/user_registrations/new.html.erb
> +                  <div>Already Registered?</div>
code indentation

2021-11-02 08:42 UTC, umairrazam commented on app/views/spree/user_registrations/new.html.erb
> +                     <div class="product-img">
code indentation

2021-11-02 08:42 UTC, umairrazam commented on app/views/spree/user_registrations/new.html.erb
> +                        <%= image_tag 'product-thumb-2.jpg', alt: "" %>
code indentation

2021-11-02 08:43 UTC, umairrazam commented on app/views/spree/user_sessions/new.html.erb
> +                        <%= image_tag 'product-thumb-1.jpg', alt: "" %>
code indentation

2021-11-04 08:30 UTC, umairrazam commented on app/views/spree/layouts/spree_application.html.erb
> +         <%= render partial: 'spree/shared/sidebar' if content_for? :sidebar %>
indentation issues divs are not properly closed see the body tag is not closed correctly

2021-11-04 08:32 UTC, umairrazam commented on app/views/spree/shared/_header.html.erb
>          <figure id="logo" class="col-md-4 col-sm-3" data-hook>
logo div is not present please verify?

2021-11-04 08:34 UTC, umairrazam commented on app/views/spree/shared/_nav_bar.html.erb
>    <ul id="nav-bar" class="nav navbar-nav navbar-right" data-hook>
id nav-bar is missing in design

2021-11-04 08:35 UTC, umairrazam commented on app/views/spree/shared/_upper_footer.html.erb
> +<div class="row no-gutters">
indentation issue

2021-11-04 08:36 UTC, umairrazam commented on app/views/spree/shared/_user_form.html.erb
> + <!-- <fieldset id="password-credentials">
id is missing "password-credentials"

2021-11-04 08:39 UTC, umairrazam commented on app/views/spree/user_registrations/new.html.erb
> +                     <div>Already Registered?</div>
indentation issue

2021-11-08 06:39 UTC, yaseeniqbal575 commented on app/views/spree/layouts/spree_application.html.erb
> +         <div>
This is an extra div.  As its not present in. template

2021-11-08 06:39 UTC, yaseeniqbal575 commented on app/views/spree/layouts/spree_application.html.erb
> +            <div  data-hook>
Remove this as well

2021-11-08 06:42 UTC, yaseeniqbal575 commented on app/views/spree/layouts/spree_application.html.erb
> +   <%= render partial: 'spree/shared/head' %>
Correct the indentation

2021-11-08 06:47 UTC, yaseeniqbal575 commented on app/views/spree/shared/_header.html.erb
> +<header id="header" data-hook>
This spree default id: "spree-header" is missing. Add this id to div under nav tag

2021-11-08 06:49 UTC, yaseeniqbal575 commented on app/views/spree/shared/_header.html.erb
>            <%= logo %>
Need to comment this line

2021-11-08 07:01 UTC, yaseeniqbal575 commented on app/views/spree/shared/_main_nav_bar.html.erb
>  <nav class="col-md-12">
The default spree code is missing. So i cant review this file.

2021-11-08 07:02 UTC, yaseeniqbal575 commented on app/views/spree/shared/_login.html.erb
> +<!-- <%= form_for Spree::User.new, as: :spree_user, url: spree.create_new_session_path do |f| %>
Default spree code is not commented well.

2021-11-08 07:10 UTC, yaseeniqbal575 commented on app/views/spree/shared/_header.html.erb
> +  <nav class="navbar navbar-expand-xl" id="top-nav-bar">
This nav bar section should be inside nav_bar partial instead of header partial

2021-11-08 07:12 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +      <div class="col-xl-10 position-static">
This id="nav-bar" is missing

2021-11-08 07:16 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +          <div class="quick-menu ml-auto">
The default spree id="search-bar" is missing

2021-11-08 07:16 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +      <div class="col-xl-10 position-static">
Indentation is not GOOD.....

2021-11-08 07:19 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +              <% if spree_current_user.present? %>
Please remove this new nav item  here  and add login and logout check on this item
<img width="83" alt="Screen Shot 2021-11-08 at 12 20 02 PM" src="https://user-images.githubusercontent.com/78048076/140699740-f4a48873-697f-4a97-9324-f11a17d95ff5.png">

2021-11-08 07:20 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +            <a class="nav-search tablet-visible" href="#"><span>Find</span></a> <a class="nav-profile tablet-hide" href="#"><span>Log In</span></a> <a class="nav-cart" href="#"><span>Cart</span><smal
Make text login/logout dynamic based upon user authentication

2021-11-08 07:24 UTC, yaseeniqbal575 commented on app/views/spree/shared/_registration_header.html.erb
> +<nav class="breadcrumb-wrap d-flex flex-wrap align-items-center justify-content-between">
Remove this breadcrumb code here and call spree breadcrumb partial instead. Please discuss with Umer.

2021-11-08 07:25 UTC, yaseeniqbal575 commented on app/views/spree/shared/_registration_header.html.erb
> +<h1 class="title mb-0">Registration</h1>
Remove this partial and move these two line to devise -> signUp form file.

<h1 class="title mb-0">Registration</h1>
<div class="sm-title mb-20">It looks like you’re new here. We need a bit more info...</div>

2021-11-08 07:28 UTC, yaseeniqbal575 commented on app/views/spree/shared/_search.html.erb
> +<!-- <#% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
Spree default code is not commented Well

2021-11-08 07:30 UTC, yaseeniqbal575 commented on app/views/spree/shared/_search.html.erb
> +      <%= search_field_tag :keywords, params[:keywords], placeholder: Spree.t(:search), class: "form-control" %>
Add this text: 'Search...' against this translation key : Spree.t(:search). Please discuss with Umer

2021-11-08 07:30 UTC, yaseeniqbal575 commented on app/views/spree/shared/_sign_in_header.html.erb
> +<nav class="breadcrumb-wrap d-flex flex-wrap align-items-center justify-content-between">
Remove  nav tag  and add breadcrumb partial here. Discuss with Umer.

2021-11-08 07:31 UTC, yaseeniqbal575 commented on app/views/spree/shared/_sign_in_header.html.erb
> +<h1 class="title">Sign In</h1>
Remove this partial and move the bewlo 2 line into devise -> User signin file.
<h1 class="title">Sign In</h1>
<div class="signin-note">Welcome to our new site. If you had an account on our previous system, please reset your password to access the new system by click <%= link_to Spree.t(:forgot_your_password?), spree.recover_password_path %>. Contact us if you need further assistance.</div>

2021-11-08 07:32 UTC, yaseeniqbal575 commented on app/views/spree/shared/_user_form.html.erb
> + <!-- <fieldset id="password-credentials">
Default spree code is not commented Well.

2021-11-08 07:35 UTC, yaseeniqbal575 commented on app/views/spree/user_sessions/new.html.erb
> -<% @body_id = 'login' %>
Default code is not commented well.

2021-11-08 07:43 UTC, yaseeniqbal575 commented on app/views/spree/user_sessions/new.html.erb
> +               <%= render :partial => 'spree/shared/login' %>
The default spree flash msg div is missing. Please add above  this partial: <%= render :partial => 'spree/shared/login' %> 


<%#if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% #end %>

2021-11-08 07:44 UTC, yaseeniqbal575 commented on app/views/spree/shared/_login.html.erb
> -<%= form_for Spree::User.new, as: :spree_user, url: spree.create_new_session_path do |f| %>
Default spree code is not commented well.

2021-11-08 07:44 UTC, yaseeniqbal575 commented on app/views/spree/shared/_login.html.erb
> +  <%= render :partial => 'spree/shared/sign_in_header' %>
Remove this partial

2021-11-08 07:45 UTC, yaseeniqbal575 commented on app/views/spree/shared/_login.html.erb
> +  <fieldset id="password-credentials">
Remove the 'fieldset' tag. As i cant see this tag inside template
<img width="1054" alt="Screen Shot 2021-11-08 at 12 45 38 PM" src="https://user-images.githubusercontent.com/78048076/140702914-25f26802-3686-497b-806b-48c46a7e628d.png">

2021-11-08 07:47 UTC, yaseeniqbal575 commented on app/views/spree/shared/_login.html.erb
> +      <%= f.email_field :email, class: 'form-control username-control', tabindex: 1, placeholder: Spree.t(:email) %>
Add this text: 'Email Address*' against this key: Spree.t(:email). Please dnt remove the key .Add the text inside local file.

2021-11-08 14:27 UTC, umairrazam commented on app/views/spree/shared/_header.html.erb
> +<header id="header" data-hook>
div id is missing

2021-11-09 06:30 UTC, yaseeniqbal575 commented on app/views/spree/shared/_main_nav_bar.html.erb
> +<a class="nav-cart" id="link-to-cart" data-hook href="#"><span>Cart</span><small class="cart-counter">4</small></a>
Add link to cart icon and it should redirect to /cart page after click on cart icon

2021-11-09 07:08 UTC, yaseeniqbal575 requested changes

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/shared/_main_nav_bar.html.erb
> +<a class="mobile-menu-link collapsed tablet-visible" id="home-link" href="#" data-toggle="collapse" data-target=".mobile-menu" area-expanded="false"><span>Menu</span></a>
This id should be add to home link. This is not the home link. Please add this id to logo div. As the logo div is the home link

id="home-link"

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +          <%= render partial: 'spree/shared/main_nav_bar' %>
Delete the main nav bar partial and add the code here. In this templated we only have a One navbar.

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/shared/_nav_bar.html.erb
> +        <div class="quick-menu ml-auto" id="search-bar" data-hook id="main-nav-bar">
add this  id="search-bar" inside search-bar partial. As inside this div, we also have a cart link

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/shared/_user_form.html.erb
> +<h1 class="title mb-0">Registration</h1>
These 2 lines shouldnt be here. Its a shared partial and use anothers forms as well. So only form fields will be in that partial

Add registeration form template file: app/views/spree/user_registrations/new.html.erb


<h1 class="title mb-0">Registration</h1>
<div class="sm-title mb-20">It looks like you’re new here. We need a bit more info...</div>

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/shared/_user_form.html.erb
> +<fieldset id="password-credentials">
There is no fieldset tag inside template form so why we added this?????

![Uploading Screen Shot 2021-11-09 at 11.40.03 AM.png…]()

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/user_passwords/edit.html.erb
> +                    <div class="form-group mb-20">
Why the 2 fields in single div. Should be separated div for each field

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/user_passwords/new.html.erb
> +                  <h1 class="title">Forgot Password?</h1>
Add this line <%= Spree.t(:forgot_password) %> instead of simple text : Forgot Password?

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/user_registrations/new.html.erb
> +                     <%= link_to root_path  do%>
Remove the link to for now.

2021-11-09 07:08 UTC, yaseeniqbal575 commented on app/views/spree/user_registrations/new.html.erb
> +                     <%= link_to root_path  do%>
remove the link_to for now. Later we will add original products path

2021-11-10 07:35 UTC, yaseeniqbal575 approved these changes

2021-11-10 07:35 UTC, merged